apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlserver-pv
spec:
  storageClassName: {{ .Values.sqlserver.volume.storageClass.name }}
  capacity:
    storage: {{ .Values.sqlserver.volume.storage }}
  accessModes:
  - {{ .Values.sqlserver.volume.accessMode }}
  hostPath:
    path: {{ .Values.sqlserver.volume.mountPath }}

