apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.angular.cluster.name }}
  labels: 
    group: {{ .Values.angular.group }}
spec:
  selector:             
    app: {{ .Values.angular.name }}
  ports:
    - name: default
      protocol: {{ .Values.angular.cluster.protocol }}
      port: {{ .Values.angular.cluster.port }}       
      targetPort: {{ .Values.angular.cluster.port }}
