replicaCount: 1
sqlserver:
  name: sqlserver
  group: db
  protocol: TCP
  port: 1433

  container:
    image: mcr.microsoft.com/mssql/server:2019-latest
    pullPolicy: IfNotPresent
    env:
      - name: MSSQL_PID
        value: "Express"
      - name: ACCEPT_EULA
        value: "Y"
      # Password secret should be added by the command below:
      # "kubectl create secret generic sqlserver --from-literal=SA_PASSWORD='Str0ngPassword!'"
      - name: MSSQL_SA_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sqlserver
            key: SA_PASSWORD

  cluster:
    name: sqlserver-clusterip

  volume:
    name: sqlserver-storage
    mountPath: /var/opt/mssql/data
    accessMode: ReadWriteOnce
    storage: 20Gi
    storageClass:
      kind: StorageClass
      name: default
      mode: WaitForFirstConsumer
    pv:
      name: sqlserver-pv
    pvc:
      name: sqlserver-claim
