apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
      group: {{ .Values.redis.group }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.name }}
        group: {{ .Values.redis.group }}
    spec:
      containers:
        - name: {{ .Values.redis.name }}
          image: {{ .Values.redis.container.image }}
          imagePullPolicy: {{ .Values.redis.container.pullPolicy }}
          ports:
            - containerPort: {{ .Values.redis.port }}
