app:
  name: client-angular
  group: frontend
  container:
    image: alexanderkarpovich/heracles-store-client-angular
    port: 80
  cluster:
    name: client-angular-clusterip
    type: ClusterIP
    ports:
      - name: client-angular-default
        protocol: TCP
        port: 80
        targetPort: 80