apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.cluster.name }}
  labels: 
    group: {{ .Values.app.group }}
spec:
  selector:             
    app: {{ .Values.app.name }}
  ports:
  {{- range .Values.app.cluster.ports}}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}       
      targetPort: {{ .targetPort }}
  {{- end}}
